### ISSUE TITLE
whippet deps install --ignore-hash

### ISSUE THREAD

**Issue by mallorydxw** [dxw/whippet#121] opened 2018-05-09 12:33 UTC
Allow ignoring the case when `whippet.json` has been updated but `whippet deps update` has not been run.

This option would be used by `chef` and prevent a mismatched hash from causing a build to fail.

**Comment by snim2** [comment] 2023-09-25 08:11
I would prefer us not to commit `whippet.json` files to repos that do not have matching lockfiles, so I tend to see this as a feature, not a bug. Currently we have a GitHub action that runs `whippet deps validate` to catch these problems, and for our own use that's probably enough. Closing.

**Closed by snim2** 2023-09-25 08:11 UTC
