### ISSUE TITLE
plugins install tries to parse whippet.json as INI

### ISSUE THREAD

**Issue by mallorydxw** [dxw/whippet#74] opened 2016-08-05 16:56 UTC
```
% whippet plugins install                                                                                          
The plugins subcommand is deprecated and will be removed in a future release.

To migrate a `plugins` file to a `whippet.json` file, run the following:
  $ whippet deps migrate

Once you have a `whippet.json` file, you can run the following instead of `whippet plugins upgrade`:
  $ whippet deps update

And the following instead of `whippet plugins install`:
  $ whippet deps install


PHP Warning:  syntax error, unexpected '{' in /workbench/src/twinkie.dxw.net/ons/app/whippet.json on line 1
 in /workbench/src/github.com/dxw/whippet/src/Modules/Helpers/ManifestIo.php on line 25
PHP Stack trace:
PHP   1. {main}() /workbench/src/github.com/dxw/whippet/bin/whippet:0
PHP   2. RubbishThorClone->start() /workbench/src/github.com/dxw/whippet/bin/whippet:26
PHP   3. Dxw\Whippet\Whippet->plugins() /workbench/src/github.com/dxw/whippet/vendor/dxw/rubbishthorclone/rubbish_thor_clone.class.php:69
PHP   4. RubbishThorClone->start() /workbench/src/github.com/dxw/whippet/src/Whippet.php:32
PHP   5. Dxw\Whippet\Modules\Plugin->install() /workbench/src/github.com/dxw/whippet/vendor/dxw/rubbishthorclone/rubbish_thor_clone.class.php:69
PHP   6. Dxw\Whippet\Modules\Plugin->load_plugins_manifest() /workbench/src/github.com/dxw/whippet/src/Modules/Plugin.php:61
PHP   7. parse_ini_file() /workbench/src/github.com/dxw/whippet/src/Modules/Helpers/ManifestIo.php:25
Unable to parse Plugins file
```

**Comment by snim2** [comment] 2023-09-18 07:32
Cannot reproduce. Closing.

**Closed by snim2** 2023-09-18 07:32 UTC
Labels: bug, module/plugin
