### ISSUE TITLE
Removed plugins persist in deploy

### ISSUE THREAD

**Issue by harry-m** [dxw/whippet#1] opened 2014-07-30 09:56 UTC
_Moving this here, so it's not in my email._

On 24/06/2014 20:18, Lee Maguire wrote:

> Removing a plugin from app/plugins, running “whippet plugins upgrade” seems to remove the plugin - but it persists on the server.
> 
> e.g. I removed jw-player nhs-hee/app - but it’s still there. When I look at /app/wp-content/plugins I see that jw-player sticks around - and just gets deployed along with the rest of them.
> 
> This is bad, unexpected, one of the issues we had with the previous deployment scheme.
> 
> Workaround is to manually delete the plugin in both locations

On 25/06/2014, Harry Metcalfe wrote:

> I think that might be expected behaviour. Whenever you make a change to plugins you need to run plugins install so that the change is applied in plugins.lock.
> 
> I haven't thought through what happens if you remove a plugin, don't install, and then run update. But If the plugin you removed from plugins is still in plugins.lock, then I think it is correct behaviour for whippet to continue deploying it.
> 
> Does the deploy process need a tweak here, or does running whippet plugins install after you remove the plugin from plugins solve the problem?

On 26/06/2014 20:18, Lee Maguire wrote:

> I ran plugins install. The plugin was removed from plugins.lock but persisted on the server.

**Comment by tomdxw** [comment] 2016-04-07 13:07
This is being worked on in #34.

**Comment by snim2** [comment] 2023-09-25 13:15
This is still the default behaviour, but this issue is in part a duplicate of #80. I'm going to close this and add some of the discussion here to that thread.

**Closed by snim2** 2023-09-25 13:15 UTC
Labels: bug, module/deploy, has PR
