### ISSUE TITLE
"whippet plugins install" sometimes modifies plugins.lock

### ISSUE THREAD

**Issue by tomdxw** [dxw/whippet#5] opened 2015-02-03 14:32 UTC
The documentation claims "Deploys the current set of plugins into your project", so modification should not be necessary.

**Comment by harry-m** [comment] 2015-03-13 13:02
That is interesting. Can you reproduce, or see an obvious code path? What was the diff?

**Comment by tomdxw** [comment] 2015-03-13 21:04
In one project it's removed a newline from the end of plugins.lock. That's easy to reproduce.

But I'm fairly sure in another project it modified the commit hashes.

**Comment by harry-m** [comment] 2015-03-16 12:37
Ok. Can you have a quick look at the code and see if you can find the newline inconsistency?

I think the latter issue may have to wait for some reproduction steps.

**Comment by dgmstuart** [comment] 2015-03-17 14:35
IIRC the behaviour is intended to imitate bundler: i.e. if all plugins are already installed then nothing changes, but if a plugin isn't yet installed then a new hash will be added.

The newline might be my bad

**Comment by tomdxw** [comment] 2015-03-23 13:58
I can reproduce it now.

Start with this (plus the mandatory wp-content/plugins, wp-content/themes, and config directories): https://gist.github.com/tomdxw/317b60fcbaf1c2bc3afb

Run "whippet plugins install"

End up with this: https://gist.github.com/tomdxw/52c76be2e8b53e757b21

> IIRC the behaviour is intended to imitate bundler: i.e. if all plugins are already installed then nothing changes, but if a plugin isn't yet installed then a new hash will be added.

I can think of an instance where that would go wrong:

1. A developer adds a line to plugins to install a new plugin and they neglect to run "whippet plugins install". They push to staging and it works. So they push to production and it still works.
1. A week later the plugin author makes a major release.
1. The site stops working the next time somebody pushes because of a backwards-incompatible change in the plugin.

**Comment by harry-m** [comment] 2015-03-23 14:08
When you say "Start with this" do you mean the directory as it stands after doing ```whippet generate app```?

How did that initial plugins.lock get generated?

**Comment by tomdxw** [comment] 2015-03-23 14:43
> When you say "Start with this" do you mean the directory as it stands after doing whippet generate app?

I mean do this:

    mkdir testdir && cd testdir && mkdir -p config wp-content/plugnis wp-content/themes && wget https://gist.githubusercontent.com/tomdxw/317b60fcbaf1c2bc3afb/raw/ec0db20dd55a292dff627076d3fad7e7033063f1/.gitignore && wget https://gist.githubusercontent.com/tomdxw/317b60fcbaf1c2bc3afb/raw/d67a4b7f7a4924fc065b4bdb3935f1f510755f70/plugins && wget https://gist.githubusercontent.com/tomdxw/317b60fcbaf1c2bc3afb/raw/02043d49eedb0931e80d51632b007ca5ec4abb55/plugins.lock

> How did that initial plugins.lock get generated?

With "whippet plugins install". The app repo which I reproduced this problem in today was one in which the most recently merged hotfix added two lines to plugin but didn't modify plugins.lock or .gitignore (i.e. somebody forgot to run "whippet plugins install").

**Comment by harry-m** [comment] 2015-03-23 16:13
So if I wget those files and then run whippet plugins install I would expect it to update plugins.lock. From its perspective there is a new plugin there.

How did you get those files in the first place? That's the bit I can't reproduce.

**Comment by tomdxw** [comment] 2015-03-23 20:40
> How did you get those files in the first place? That's the bit I can't reproduce.

I pulled. Somebody had added a couple of lines to `plugins` but they had not modified `plugins.lock` or `.gitignore`.

**Comment by harry-m** [comment] 2015-03-24 10:21
Hmm. Not sure we can avoid that? Bit strange to add to plugins without running whippet but if someone does, what's do be done?

Same thing would happen if you added a line to Gemfile and didn't run bundle, I think? 

(cc @dgmstuart)

**Comment by tomdxw** [comment] 2015-03-24 12:24
> Not sure we can avoid that?

If we make "whippet plugins install" ignore `plugins` then when somebody does that in future they'll push and realise they've made a mistake.

If we do that then we'll always have the git hash in `plugins.lock` and we'll avoid the potentially disastrous situation I described to Duncan above.

**Comment by dgmstuart** [comment] 2015-03-24 19:23
> Same thing would happen if you added a line to Gemfile and didn't run bundle, I think?

No, but the difference is that gems generally have dependencies, and the versions of all of those dependencies are part of the definition of your app. You also have weak version specifications (e.g. `>1.2`). Even without dependencies, and exact version number dependencies in the gemfile you still need a lockfile. 

I suppose you could ' Trick' bundler by carefully constructing a valid lockfile, but that's a pretty pathological case.

The difference is that if you have gem versions installed on your machine which are compatible with your gemspec, then Bundler will use those and won't go and re-fetch them from rubygems.

With Bundler you do get twisty conflicts if people commit updates to the gemfile and forget to commit updates to the lockfile (you end up out of sync). There's no magic way round that: you just need to always remember to commit them together.

**Comment by harry-m** [comment] 2015-03-25 10:02
> With Bundler you do get twisty conflicts if people commit updates to the gemfile and forget to commit 
> updates to the lockfile (you end up out of sync). There's no magic way round that: you just need to
> always remember to commit them together."

That's exactly the situation here though I think? There's a line in plugins but no equivalent section in plugins.lock?

I think Tom's just pulled a repo where someone hasn't run whippet plugins install, and there's no bug here.

All agree?

**Comment by dgmstuart** [comment] 2015-03-25 11:12
Like you said in #15, whippet needs to not run if there's no lockfile

**Comment by harry-m** [comment] 2016-03-31 09:59
Agree. Closing this, we'll address the problem in #15.

**Closed by harry-m** 2016-03-31 09:59 UTC
Labels: bug, module/plugin
